### ISSUE TITLE
 r50-c4 config

### ISSUE THREAD

**Issue by UcanSee** [NVlabs/wetectron#21]
Thanks for sharing such wonderful work!
Recently I want to try experiments on coco with r50-c4 backbone but I don't know how to set the configuration, can you share the config you used?
looking forward your reply!

**Comment by jason718** [comment]
The current code haven't fully supported R50-C4 on COCO as we haven't include the Seq. batch back-propagation module. If you run it, you may get OOM error.

FYI, the configs we were using is:
```
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50" 
  WSOD_ON: True
  FASTER_RCNN: False
  ROI_HEADS:
    SCORE_THRESH: 0.0
    NMS: 0.3
  ROI_WEAK_HEAD:
    PREDICTOR: "MISTPredictor"
    LOSS: "RoIRegLoss"
    OICR_P: 0.15
    REGRESS_ON: True
DATASETS:
  TRAIN: ("coco_2014_train",)
  TEST: ("coco_2014_val",)
PROPOSAL_FILES:
  TRAIN: ('proposal/MCG-coco_2014_train-boxes.pkl',)
  TEST:  ('proposal/MCG-coco_2014_val-boxes.pkl',)
DATALOADER:
  SIZE_DIVISIBILITY: 32
INPUT:
  MIN_SIZE_TRAIN: (480, 576, 688, 864, 1000, 1200) 
  MAX_SIZE_TRAIN: 2000
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 2000
SOLVER:
  IMS_PER_BATCH: 8 
  BASE_LR: 0.01 
  WEIGHT_DECAY: 0.0001
  STEPS: (90000, 120000)
  MAX_ITER: 130000
  CHECKPOINT_PERIOD: 10000
TEST:
  BBOX_AUG:
    ENABLED: True
    HEUR: "AVG"
    H_FLIP: True
    SCALES: (480, 576, 688, 864, 1000, 1200) 
    MAX_SIZE: 2000
    SCALE_H_FLIP: True
```
